/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpboitesdialogue;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp-Pc
 */
public class NewJFrameDialogue extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameDialogue
     */
    public NewJFrameDialogue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_message = new javax.swing.JButton();
        jButton_warning = new javax.swing.JButton();
        jButton_erreur = new javax.swing.JButton();
        jButton_info = new javax.swing.JButton();
        jButton_conf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_message.setText("Message");
        jButton_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_messageActionPerformed(evt);
            }
        });

        jButton_warning.setText("Warning");
        jButton_warning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_warningActionPerformed(evt);
            }
        });

        jButton_erreur.setText("Erreur");
        jButton_erreur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_erreurActionPerformed(evt);
            }
        });

        jButton_info.setText("Information ");
        jButton_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_infoActionPerformed(evt);
            }
        });

        jButton_conf.setText("Confirmation");
        jButton_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_erreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_conf, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton_message)
                .addGap(29, 29, 29)
                .addComponent(jButton_warning)
                .addGap(32, 32, 32)
                .addComponent(jButton_erreur)
                .addGap(30, 30, 30)
                .addComponent(jButton_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton_conf)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_messageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Welcome to NetBeans!");
        
        
    }//GEN-LAST:event_jButton_messageActionPerformed

    private void jButton_warningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_warningActionPerformed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(
                        this,
                        "Echec de connexion!",
                        "Alert",
                        JOptionPane.WARNING_MESSAGE
    );
    }//GEN-LAST:event_jButton_warningActionPerformed

    private void jButton_erreurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_erreurActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
                        this,
                        "Alertttttttttttttttttttttt",
                        "Alert",
                        JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton_erreurActionPerformed

    private void jButton_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_infoActionPerformed
        // TODO add your handling code here:
            String nom = JOptionPane.showInputDialog(this,"Entrez votre nom:");
            System.out.println(nom);
             JOptionPane.showMessageDialog(
                        this,
                        nom );
            
            
            
            

    }//GEN-LAST:event_jButton_infoActionPerformed

    private void jButton_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confActionPerformed
        // TODO add your handling code here:
            int res = JOptionPane.showConfirmDialog(this,"Etes-vous sur?");

            if(res == JOptionPane.YES_OPTION)
            {
                System.exit(0);
                this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
                System.out.println("................");
            }else if(res == JOptionPane.NO_OPTION)
            {    
                System.out.println("..hjhkjjhj.");
            }
    }//GEN-LAST:event_jButton_confActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameDialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameDialogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_conf;
    private javax.swing.JButton jButton_erreur;
    private javax.swing.JButton jButton_info;
    private javax.swing.JButton jButton_message;
    private javax.swing.JButton jButton_warning;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
