/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author deathscythe
 */
public class AddStudent extends javax.swing.JFrame {
    private BookService bookService;
    /**
     * Creates new form AddStudent
     */
    public AddStudent() throws SQLException {
        initComponents();
        bookService = new BookService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        YearOfStudyLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        yearOfStudy = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        jPanel1.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 50, 95, 57));

        YearOfStudyLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        YearOfStudyLabel.setForeground(new java.awt.Color(255, 255, 255));
        YearOfStudyLabel.setText("Year Of Study:");
        jPanel1.add(YearOfStudyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 173, 120, 57));

        lastNameLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 50, 120, 57));

        idLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("ID:");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 173, 95, 57));

        firstName.setBackground(new java.awt.Color(211, 154, 228));
        firstName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 50, 204, 57));

        lastName.setBackground(new java.awt.Color(211, 154, 228));
        lastName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 50, 204, 57));

        id.setBackground(new java.awt.Color(211, 154, 228));
        id.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 173, 204, 57));

        yearOfStudy.setBackground(new java.awt.Color(211, 154, 228));
        yearOfStudy.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(yearOfStudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 173, 204, 57));

        addStudentButton.setBackground(new java.awt.Color(190, 117, 212));
        addStudentButton.setForeground(new java.awt.Color(0, 0, 0));
        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 291, 144, 62));

        cancelButton.setBackground(new java.awt.Color(190, 117, 212));
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 291, 144, 62));

        jLabel1.setBackground(new java.awt.Color(190, 117, 212));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/360_F_917125159_XvccmUDmfINJs1n85nux2tEZlg3gu8Ty.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        int student_id = Integer.parseInt(id.getText());
        String student_first_name = firstName.getText();
        String student_last_name = lastName.getText();
        int student_year_of_study = Integer.parseInt(yearOfStudy.getText());
        Student student = new Student(student_id, student_first_name, student_last_name, student_year_of_study);
        try {
            bookService.addStudent(student);
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddStudent().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel YearOfStudyLabel;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField yearOfStudy;
    // End of variables declaration//GEN-END:variables
}
