/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author deathscythe
 */
public class BorrowBook extends javax.swing.JFrame {
    private BookService bookService;
    /**
     * Creates new form BorrowBook
     */
    public BorrowBook() throws SQLException {
        initComponents();
        bookService = new BookService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentIdLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        borrowButton = new javax.swing.JButton();
        borrowPeriodLabel = new javax.swing.JLabel();
        borrowPeriod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentIdLabel.setText("Student ID: ");
        jPanel1.add(studentIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 61, 140, 56));

        isbnLabel.setForeground(new java.awt.Color(255, 255, 255));
        isbnLabel.setText("ISBN:");
        jPanel1.add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, 56));

        studentId.setBackground(new java.awt.Color(215, 177, 236));
        studentId.setForeground(new java.awt.Color(0, 0, 0));
        studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdActionPerformed(evt);
            }
        });
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 62, 353, 56));

        isbn.setBackground(new java.awt.Color(215, 177, 236));
        isbn.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 161, 353, 56));

        cancelButton.setBackground(new java.awt.Color(190, 117, 212));
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 382, 126, 57));

        borrowButton.setBackground(new java.awt.Color(190, 117, 212));
        borrowButton.setForeground(new java.awt.Color(0, 0, 0));
        borrowButton.setText("Borrow Book");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(borrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 382, 124, 57));

        borrowPeriodLabel.setForeground(new java.awt.Color(255, 255, 255));
        borrowPeriodLabel.setText("Borrow period (days) : ");
        jPanel1.add(borrowPeriodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 262, -1, 56));

        borrowPeriod.setBackground(new java.awt.Color(215, 177, 236));
        borrowPeriod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(borrowPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 263, 353, 56));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/360_F_917125159_XvccmUDmfINJs1n85nux2tEZlg3gu8Ty (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        int student_id = Integer.parseInt(studentId.getText());
        String book_isbn = isbn.getText();
        int borrow_period = Integer.parseInt(borrowPeriod.getText());
        try {
            bookService.borrowBook(student_id, book_isbn, borrow_period);
        } catch (SQLException ex) {
            Logger.getLogger(BorrowBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_borrowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BorrowBook().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BorrowBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowButton;
    private javax.swing.JTextField borrowPeriod;
    private javax.swing.JLabel borrowPeriodLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField studentId;
    private javax.swing.JLabel studentIdLabel;
    // End of variables declaration//GEN-END:variables
}
